### ISSUE TITLE
NPX usage

### ISSUE THREAD

**Issue by jacksteamdev** [ffflorian/which-os#161]
Any suggestions on using this with NPX?

I'd love to suggest a cli command like `npx whichos` in my issue template to make it easy for a contributer to copy/paste info about their os.

**Comment by ffflorian** [comment]
Hi @jacksteamdev, right now there is another [package called which-os](https://www.npmjs.com/package/which-os) so we can't use `npx which-os` to use my package.

I could imagine renaming my package to e.g. `os-info` and the command would be e.g. `os-info which-os` or `os-info is-linux`.

What do you think?

**Comment by jacksteamdev** [comment]
@ffflorian Sounds good to me!

**Comment by ffflorian** [comment]
@jacksteamdev you can now run `npx which-os` :tada:
